### ISSUE TITLE
Consider redirecting to HTTPS from HTTP

### ISSUE THREAD

**Issue by MHordecki** [mina86/mina86.com#1]
In this day and age, all user agents should be assumed to support encryption.

Docs: https://faq.nearlyfreespeech.net/full/enforcessl

**Comment by mina86** [comment]
My worry is about server side, not client side. Furthermore, switching to HTTPS is the trivial part. Problem is with maintaining a valid certificate. When [I’ve first enabled TLS](http://mina86.com/2016/tls-is-a-yes/) NFSN didn’t allow to generate Let’s Encrypt certificate via a cron job. Fortunately now, NFSN provides native support for Let’s Encrypt and after some testing it indeed looks stable so I might soon be able to force HTTPS on all requests.

**Comment by mina86** [comment]
I’ve enabled HTTP­->HTTPS redirect and added ``CSP``: ``upgrade-insecure-requests`` header so any rouge insecure URLs will be automatically upgraded. I’ll enable HSTS in a few days.
